"""Generate deliverables/d3_example_patient.json from the fixture.

Generated rather than hand-written, so the example record cannot drift away from the models
it claims to instantiate. Regenerate with:

    .venv/bin/python scripts_build_d3.py

and `git diff` should be empty. That is what proves the file is generated: if it were
hand-maintained, regenerating would overwrite the edits.

Identifiers are made deterministic for this artifact — `lab_0002` rather than a 26-character
ULID. Two reasons: the output is then byte-identical across runs, and a reviewer tracing
`report_id` to `result_ids` can actually read it. The prefix still says what kind of record it
is (model_design.md §8). Production uses real ULIDs; only this script substitutes a counter,
and it does so *before* any model is imported, so `prompt_digest` remains a genuine hash of
the prompt that was really assembled from these ids rather than a placeholder.
"""

import itertools
import json
from pathlib import Path

import pai3.ids

_COUNTERS: dict[str, itertools.count] = {}


def _deterministic_new_id(prefix: str) -> str:
    if not prefix or "_" in prefix:
        raise ValueError(f"invalid prefix: {prefix!r}")
    counter = _COUNTERS.setdefault(prefix, itertools.count(1))
    return f"{prefix}_{next(counter):04d}"


pai3.ids.new_id = _deterministic_new_id  # must precede the imports below

from mock.patient_fixture import build_fixture
from pai3.ai.adapter import LocalInferenceAdapter
from pai3.ai.generators import StubGenerator
from pai3.ai.scope import authorize_ai_read
from pai3.readmodels.timeline import build_timeline
from pai3.validation import check_condition, check_lab_result, check_medication

OUT = Path("deliverables/d3_example_patient.json")


def main() -> None:
    fx = build_fixture(with_conflicting_glucose=True)
    scope = authorize_ai_read(fx.patient.id, fx.consents, fx.now)
    # The stub, deliberately: this record must be byte-reproducible, and a real model is not.
    # The artifact reports engine=stub and a model_id that says so, so nothing here can be
    # read as evidence that inference ran. For a record produced by a real local model, see
    # deliverables/d8_real_inference/ and scripts_run_ollama.py.
    adapter = LocalInferenceAdapter(StubGenerator())
    brief = adapter.build_brief(fx, scope, budget=50)

    # Layer-2 validation over the record, so the flags shown are the ones the validators
    # actually raise rather than a hand-picked selection.
    derived_flags = []
    for cond in fx.conditions:
        derived_flags += check_condition(cond, fx.provider_actor, fx.now)
    for med in fx.medications:
        derived_flags += check_medication(med, fx.provider_actor, fx.now)
    for lab in fx.labs:
        derived_flags += check_lab_result(lab, fx.provider_actor, fx.now)

    record = {
        "_note": (
            "Entirely fictional. Generated from mock/patient_fixture.py by "
            "scripts_build_d3.py, which also makes identifiers deterministic so the file is "
            "reproducible; production uses ULIDs. NO INFERENCE RAN for this record: the "
            "ai_layer section was produced by a deterministic stand-in, which is why it "
            "reports engine=stub. A record generated by a real local model is in "
            "deliverables/d8_real_inference/."
        ),
        "_sections": {
            "canonical": "accepted clinical fact; every value names who vouched for it",
            "derived": "read-models, never stored (model_design.md §6.13, §9.4)",
            "ai_layer": "generated, references canonical by id and version; never the reverse",
        },
        "canonical": {
            "patient": fx.patient.model_dump(mode="json"),
            "provider": fx.provider.model_dump(mode="json"),
            "consents": [c.model_dump(mode="json") for c in fx.consents],
            "encounters": [e.model_dump(mode="json") for e in fx.encounters],
            "conditions": [c.model_dump(mode="json") for c in fx.conditions],
            "symptoms": [s.model_dump(mode="json") for s in fx.symptoms],
            "medications": [m.model_dump(mode="json") for m in fx.medications],
            "supplements": [s.model_dump(mode="json") for s in fx.supplements],
            "allergies": [a.model_dump(mode="json") for a in fx.allergies],
            "lab_results": [lab.model_dump(mode="json") for lab in fx.labs],
            "diagnostic_reports": [r.model_dump(mode="json") for r in fx.reports],
            "vitals": [v.model_dump(mode="json") for v in fx.vitals],
            "clinical_notes": [n.model_dump(mode="json") for n in fx.notes],
            "treatment_plans": [p.model_dump(mode="json") for p in fx.plans],
            "source_references": [s.model_dump(mode="json") for s in fx.source_refs],
            "data_quality_flags": [
                f.model_dump(mode="json") for f in (*fx.flags, *derived_flags)
            ],
        },
        "derived": {
            "timeline": [
                e.model_dump(mode="json")
                for e in build_timeline(
                    encounters=fx.encounters, conditions=fx.conditions,
                    symptoms=fx.symptoms,
                    medications=fx.medications, supplements=fx.supplements,
                    labs=fx.labs, reports=fx.reports, notes=fx.notes,
                )
            ],
            "lab_trends": [t.model_dump(mode="json") for t in brief.trends],
            "pre_visit_brief": brief.model_dump(mode="json", exclude={"narrative"}),
        },
        "ai_layer": {
            "summary": brief.narrative.model_dump(mode="json") if brief.narrative else None,
            "human_review_status": (
                brief.narrative.review.value if brief.narrative else "no narrative produced"
            ),
        },
        "audit": [e.model_dump(mode="json") for e in adapter.audit_events],
    }

    OUT.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
